### ISSUE TITLE
event binding js loop causing front end performance issue.

### ISSUE THREAD

**Issue by yao9394** [catalyst/moodle-mod_hsuforum#8]
https://github.com/catalyst/moodle-mod_hsuforum/blob/MOODLE_37_STABLE/amd/src/accessibility.js#L35-L45 

The code here trying to bind keypress event, is creating event binding loop. When 100 discussions on a page, it is causing front end performance issue.

**Comment by dmitriim** [comment]
Fixed in upstream master
